# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1734, 959)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainTitle = QtWidgets.QLabel(self.centralwidget)
        self.MainTitle.setGeometry(QtCore.QRect(210, 170, 1411, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.MainTitle.setFont(font)
        self.MainTitle.setStyleSheet("QLabel#titleLabel, QLabel {\n"
"    /* Make the text bold */\n"
"    font-weight: bold;\n"
"    /* Increase the font size significantly */\n"
"    font-size: 25pt;\n"
"    /* Set a dark, high-contrast color */\n"
"     color: #4A4A4A; \n"
"    /* Center the text (if not already centered by layout) */\n"
"    text-align: center;\n"
"    /* Add a subtle drop shadow for depth */\n"
"    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);\n"
"}")
        self.MainTitle.setObjectName("MainTitle")
        self.db_extract = QtWidgets.QPushButton(self.centralwidget)
        self.db_extract.setGeometry(QtCore.QRect(440, 320, 241, 41))
        self.db_extract.setStyleSheet("/* ==== Global Button Styling ==== */\n"
"QPushButton {\n"
"    font-family: \"Segoe UI\";        /* Clean modern font */\n"
"    font-size: 10pt;                /* Slightly larger */\n"
"    font-weight: bold;              /* Makes text pop */\n"
"    color: #ffffff;                 /* White text */\n"
"    background-color: #4169E1;      /* Soft blue button */\n"
"    border: none;                   /* Removes old-style 3D border */\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"    padding: 10px 18px;             /* Comfortable click area */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005bb5;      /* Darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004a99;      /* Even darker on click */\n"
"}\n"
"\n"
"/* ==== Optional: Label and Window Styling ==== */\n"
"QLabel {\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #333333;\n"
"}\n"
"QMainWindow {\n"
"    background-color: #f4f7fb;      /* Light grayish background */\n"
"}\n"
"")
        self.db_extract.setObjectName("db_extract")
        self.db_load = QtWidgets.QPushButton(self.centralwidget)
        self.db_load.setGeometry(QtCore.QRect(760, 320, 241, 41))
        self.db_load.setStyleSheet("/* ==== Global Button Styling ==== */\n"
"QPushButton {\n"
"    font-family: \"Segoe UI\";        /* Clean modern font */\n"
"    font-size: 10pt;                /* Slightly larger */\n"
"    font-weight: bold;              /* Makes text pop */\n"
"    color: #ffffff;                 /* White text */\n"
"    background-color: #4169E1;      /* Soft blue button */\n"
"    border: none;                   /* Removes old-style 3D border */\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"    padding: 10px 18px;             /* Comfortable click area */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005bb5;      /* Darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004a99;      /* Even darker on click */\n"
"}\n"
"\n"
"/* ==== Optional: Label and Window Styling ==== */\n"
"QLabel {\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #333333;\n"
"}\n"
"QMainWindow {\n"
"    background-color: #f4f7fb;      /* Light grayish background */\n"
"}\n"
"")
        self.db_load.setObjectName("db_load")
        self.file_converter = QtWidgets.QPushButton(self.centralwidget)
        self.file_converter.setGeometry(QtCore.QRect(1100, 320, 241, 41))
        self.file_converter.setStyleSheet("/* ==== Global Button Styling ==== */\n"
"QPushButton {\n"
"    font-family: \"Segoe UI\";        /* Clean modern font */\n"
"    font-size: 10pt;                /* Slightly larger */\n"
"    font-weight: bold;              /* Makes text pop */\n"
"    color: #ffffff;                 /* White text */\n"
"    background-color: #4169E1;      /* Soft blue button */\n"
"    border: none;                   /* Removes old-style 3D border */\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"    padding: 10px 18px;             /* Comfortable click area */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005bb5;      /* Darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004a99;      /* Even darker on click */\n"
"}\n"
"\n"
"/* ==== Optional: Label and Window Styling ==== */\n"
"QLabel {\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #333333;\n"
"}\n"
"QMainWindow {\n"
"    background-color: #f4f7fb;      /* Light grayish background */\n"
"}\n"
"")
        self.file_converter.setObjectName("file_converter")
        self.adhoc_extract = QtWidgets.QPushButton(self.centralwidget)
        self.adhoc_extract.setGeometry(QtCore.QRect(440, 420, 241, 41))
        self.adhoc_extract.setStyleSheet("/* ==== Global Button Styling ==== */\n"
"QPushButton {\n"
"    font-family: \"Segoe UI\";        /* Clean modern font */\n"
"    font-size: 10pt;                /* Slightly larger */\n"
"    font-weight: bold;              /* Makes text pop */\n"
"    color: #ffffff;                 /* White text */\n"
"    background-color: #4169E1;      /* Soft blue button */\n"
"    border: none;                   /* Removes old-style 3D border */\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"    padding: 10px 18px;             /* Comfortable click area */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005bb5;      /* Darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004a99;      /* Even darker on click */\n"
"}\n"
"\n"
"/* ==== Optional: Label and Window Styling ==== */\n"
"QLabel {\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #333333;\n"
"}\n"
"QMainWindow {\n"
"    background-color: #f4f7fb;      /* Light grayish background */\n"
"}\n"
"")
        self.adhoc_extract.setObjectName("adhoc_extract")
        self.adhoc_load = QtWidgets.QPushButton(self.centralwidget)
        self.adhoc_load.setGeometry(QtCore.QRect(760, 420, 241, 41))
        self.adhoc_load.setStyleSheet("/* ==== Global Button Styling ==== */\n"
"QPushButton {\n"
"    font-family: \"Segoe UI\";        /* Clean modern font */\n"
"    font-size: 10pt;                /* Slightly larger */\n"
"    font-weight: bold;              /* Makes text pop */\n"
"    color: #ffffff;                 /* White text */\n"
"    background-color: #4169E1;      /* Soft blue button */\n"
"    border: none;                   /* Removes old-style 3D border */\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"    padding: 10px 18px;             /* Comfortable click area */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005bb5;      /* Darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004a99;      /* Even darker on click */\n"
"}\n"
"\n"
"/* ==== Optional: Label and Window Styling ==== */\n"
"QLabel {\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #333333;\n"
"}\n"
"QMainWindow {\n"
"    background-color: #f4f7fb;      /* Light grayish background */\n"
"}\n"
"")
        self.adhoc_load.setObjectName("adhoc_load")
        self.adhoc_convert = QtWidgets.QPushButton(self.centralwidget)
        self.adhoc_convert.setGeometry(QtCore.QRect(1100, 420, 241, 41))
        self.adhoc_convert.setStyleSheet("/* ==== Global Button Styling ==== */\n"
"QPushButton {\n"
"    font-family: \"Segoe UI\";        /* Clean modern font */\n"
"    font-size: 10pt;                /* Slightly larger */\n"
"    font-weight: bold;              /* Makes text pop */\n"
"    color: #ffffff;                 /* White text */\n"
"    background-color: #4169E1;      /* Soft blue button */\n"
"    border: none;                   /* Removes old-style 3D border */\n"
"    border-radius: 10px;            /* Rounded corners */\n"
"    padding: 10px 18px;             /* Comfortable click area */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005bb5;      /* Darker on hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #004a99;      /* Even darker on click */\n"
"}\n"
"\n"
"/* ==== Optional: Label and Window Styling ==== */\n"
"QLabel {\n"
"    font-family: \"Segoe UI Semibold\";\n"
"    font-size: 16pt;\n"
"    color: #333333;\n"
"}\n"
"QMainWindow {\n"
"    background-color: #f4f7fb;      /* Light grayish background */\n"
"}\n"
"")
        self.adhoc_convert.setObjectName("adhoc_convert")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1734, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MainTitle.setText(_translate("MainWindow", "                              AUTO_ETL WORKFLOW ENGINE"))
        self.db_extract.setText(_translate("MainWindow", "Database Extractor"))
        self.db_load.setText(_translate("MainWindow", "Database Loader"))
        self.file_converter.setText(_translate("MainWindow", "File Conversion"))
        self.adhoc_extract.setText(_translate("MainWindow", "Adhoc Database Extractor"))
        self.adhoc_load.setText(_translate("MainWindow", "Adhoc Database Loader"))
        self.adhoc_convert.setText(_translate("MainWindow", "Adhoc File Conversion"))
